### PR TITLE
Added user search API wrapper

### PR DESCRIPTION
**Pull request by kshehadeh**

### CODE REVIEW

**Comment by MrRefactoring** [comment]
Hi, @kshehadeh. Thanks for your PR. Can you add API for user search?

**Comment by kshehadeh** [comment]
Ugh.  Apologies.  Will update soon.

**Comment by kshehadeh** [comment]
Updated with missing files.

**Review by MrRefactoring — APPROVED** [review]

**Comment by MrRefactoring** [comment]
Thank you for the contribution!

**Comment by MrRefactoring** [comment]
Added in 0.10.0

**Pull request merged**
